Description of subplotsq
Home > plott_code > subplotsq.m
subplotsq
PURPOSE
h=subplotsq(N,i)
SYNOPSIS
function h=subplotsq(N,i)
DESCRIPTION
     h=subplotsq(N,i)
     Wrapper shortcut for producing subplots in arranged
     in a square (see code below)
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
plott_all [h, hl] = plott_all(varargin)
plott_ani [returns] = plotani(X,fs,options)
plott_handles [h,hl] = plott_handles(fname,fsubplot,varargin)
SOURCE CODE
function h=subplotsq(N,i)
%     h=subplotsq(N,i)
%
%     Wrapper shortcut for producing subplots in arranged
%     in a square (see code below)
    Ncols = ceil(sqrt(N));
    Nrows = ceil(N/Ncols);
    h=subplot(Nrows,Ncols,i);
end